version: '3'
services:
  httpd:
    build:
      context: .
      dockerfile: Dockerfile.httpd
    container_name: httpd
    ports:
      - "8080:80"
      - "1234:1234" # For auxiliary communication
    volumes:
      - "./test-page:/usr/local/apache2/htdocs/"
      - "./docker_home:/home"
    restart: always