version: '3'
services:
  httpd:
    build:
      context: .
      dockerfile: Dockerfile.httpd
    container_name: httpd
    #mem_limit: "1g"
    #mem_reservation: "512m"
    #cpus: "1"
    #cpuset: "1"
    networks:
      my_bridge_network:
        ipv4_address: 172.20.0.2
    volumes:
      - "./test-page:/usr/local/apache2/htdocs/"
      - "./docker_home:/home"
    #restart: always
networks:
  my_bridge_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
